"""Rebuild standalone Oracle install/upgrade scripts from canonical SQL modules."""
from pathlib import Path
import argparse
import re

SQL = Path(__file__).resolve().parents[1] / 'sql'


def module(name):
    text = (SQL / name).read_text(encoding='utf-8-sig').strip()
    # SQL*Plus and DBeaver both accept slash-delimited PL/SQL blocks.
    if name == '06_triggers.sql':
        text = re.sub(r'END;\s*(?=CREATE OR REPLACE|$)', 'END;\n/\n\n', text)
    elif name in ('04_package_spec.sql', '05_package_body.sql', '09_upgrade_existing_db.sql'):
        text = text.rstrip('/\n ') + '\n/'
    return f'-- {name}\n{text}\n'


def generated_scripts():
    install_header = '''-- GENERATED by scripts/build_sql.py; edit the numbered source modules.
-- NEW / EMPTY SCHEMA ONLY. Use 10_upgrade_workflow.sql for an existing database.
-- Connect as the application DB_USER, not SYSTEM.
'''
    install_parts = ['01_create_tables.sql', '03_sequences.sql', '02_constraints.sql',
                     '06_triggers.sql', '07_seed_reference_data.sql', '04_package_spec.sql', '05_package_body.sql']
    install = install_header + '\n'.join(module(name) for name in install_parts)
    visit_table = (SQL / '01_create_tables.sql').read_text().split('CREATE TABLE attempt_question_visit (', 1)[1]
    visit_table = 'CREATE TABLE attempt_question_visit (' + visit_table.strip().rstrip(';')
    upgrade = '''-- GENERATED by scripts/build_sql.py; preserves application data.
-- Stop the web app, connect as its DB_USER and execute the entire script.
'''
    upgrade += module('09_upgrade_existing_db.sql')
    upgrade += "\nBEGIN\n    EXECUTE IMMEDIATE q'[" + visit_table + "]';\nEXCEPTION\n    WHEN OTHERS THEN\n        IF SQLCODE != -955 THEN RAISE; END IF;\nEND;\n/\n\n"
    upgrade += module('04_package_spec.sql') + '\n' + module('05_package_body.sql')
    verification = '''
SELECT object_name, object_type, status FROM user_objects
WHERE object_name = 'QUIZ_PLATFORM' ORDER BY object_type;
SELECT name, type, line, position, text FROM user_errors
WHERE name = 'QUIZ_PLATFORM' ORDER BY type, sequence;
'''
    return {'00_install_all.sql': install + verification,
            '10_upgrade_workflow.sql': upgrade + verification}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated files without rewriting them')
    args = parser.parse_args()
    mismatches = []
    for name, content in generated_scripts().items():
        path = SQL / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                mismatches.append(name)
        else:
            path.write_text(content, encoding='utf-8')
    if mismatches:
        raise SystemExit('Out of date: ' + ', '.join(mismatches))


if __name__ == '__main__':
    main()
