CREATE SEQUENCE seq_role START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_users START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE seq_category START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_difficulty_level START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_question_type START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_test START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_question START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_answer_option START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_question_in_test START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_test_access START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_attempt START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_answer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_answer_selected_option START WITH 1 INCREMENT BY 1;

