CREATE OR REPLACE PACKAGE quiz_platform AS
    PROCEDURE info;
    PROCEDURE register_user(p_user_name VARCHAR2, p_password VARCHAR2);
    FUNCTION register_user_id(p_user_name VARCHAR2, p_password VARCHAR2) RETURN NUMBER;
    FUNCTION login_user(p_uid NUMBER, p_password VARCHAR2) RETURN NUMBER;
    FUNCTION check_author_role(p_uid NUMBER) RETURN NUMBER;
    FUNCTION check_admin_role(p_uid NUMBER) RETURN NUMBER;
    FUNCTION get_user(p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_categories RETURN SYS_REFCURSOR;
    FUNCTION list_difficulty_levels RETURN SYS_REFCURSOR;
    FUNCTION list_question_types RETURN SYS_REFCURSOR;
    PROCEDURE create_test(p_uid_author NUMBER, p_test_name VARCHAR2, p_test_description VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_time_limit NUMBER, p_attempt_limit NUMBER, p_show_feedback NUMBER, p_question_count NUMBER);
    FUNCTION create_test_id(p_uid_author NUMBER, p_test_name VARCHAR2, p_test_description VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_time_limit NUMBER, p_attempt_limit NUMBER, p_show_feedback NUMBER, p_question_count NUMBER) RETURN NUMBER;
    PROCEDURE publish_test(p_uid_author NUMBER, p_id_test NUMBER, p_direct_call NUMBER DEFAULT 1);
    PROCEDURE generate_test_questions(p_uid_author NUMBER, p_id_test NUMBER);
    PROCEDURE add_question(p_uid_author NUMBER, p_question_text VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_type_id NUMBER, p_correct_text VARCHAR2, p_correct_number NUMBER, p_tolerance NUMBER, p_explanation VARCHAR2);
    FUNCTION add_question_id(p_uid_author NUMBER, p_question_text VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_type_id NUMBER, p_correct_text VARCHAR2, p_correct_number NUMBER, p_tolerance NUMBER, p_explanation VARCHAR2) RETURN NUMBER;
    PROCEDURE add_answer_option(p_id_question NUMBER, p_option_text VARCHAR2, p_is_correct NUMBER);
    PROCEDURE add_question_type(p_type_name VARCHAR2);
    PROCEDURE add_category(p_category_name VARCHAR2, p_category_description VARCHAR2);
    PROCEDURE add_difficulty_level(p_level_name VARCHAR2);
    PROCEDURE deactivate_question(p_id_question NUMBER, p_uid_author NUMBER);
    PROCEDURE include_question_in_test(p_uid_author NUMBER, p_id_test NUMBER, p_id_question NUMBER, p_weight NUMBER, p_order_num NUMBER, p_is_required NUMBER, p_time_limit NUMBER);
    PROCEDURE grant_test_access(p_uid_author NUMBER, p_id_test NUMBER, p_uid NUMBER);
    PROCEDURE deactivate_test_access(p_id_test NUMBER, p_uid NUMBER, p_uid_author NUMBER);
    FUNCTION check_access(p_id_test NUMBER, p_uid NUMBER) RETURN NUMBER;
    PROCEDURE start_attempt(p_id_test NUMBER, p_uid NUMBER);
    FUNCTION start_attempt_id(p_id_test NUMBER, p_uid NUMBER) RETURN NUMBER;
    PROCEDURE save_answer(p_id_attempt NUMBER, p_id_qt NUMBER, p_answer_text VARCHAR2, p_answer_number NUMBER, p_answer_time NUMBER);
    FUNCTION save_answer_id(p_id_attempt NUMBER, p_id_qt NUMBER, p_answer_text VARCHAR2, p_answer_number NUMBER, p_answer_time NUMBER) RETURN NUMBER;
    PROCEDURE save_selected_option(p_id_answer NUMBER, p_id_option NUMBER);
    FUNCTION check_answer(p_id_answer NUMBER) RETURN NUMBER;
    FUNCTION calc_answer_score(p_id_answer NUMBER) RETURN NUMBER;
    PROCEDURE finish_attempt(p_id_attempt NUMBER);
    PROCEDURE calc_result(p_id_attempt NUMBER);
    FUNCTION list_author_questions(p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_author_question(p_id_question NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_answer_options(p_id_question NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_available_tests(p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_available_test(p_id_test NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_attempt(p_id_attempt NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_questions(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_answers(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_selected_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_question_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_attempt_result(p_id_attempt NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_result_answers(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_result_selected_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_result_correct_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_user_attempts(p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_author_tests(p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_author_test(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_test_questions(p_id_test NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_selected_test_questions(p_id_test NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_question_pool(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_author_test_access_header(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_test_access(p_id_test NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_test_statistics_summary(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_test_statistics_questions(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_users(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_tests(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_questions(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_admin_statistics(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    PROCEDURE show_result(p_id_attempt NUMBER);
    PROCEDURE show_user_attempts(p_uid NUMBER);
    PROCEDURE show_test_statistics(p_id_test NUMBER);
END quiz_platform;
/
