-- GENERATED by scripts/build_sql.py; preserves application data.
-- Stop the web app, connect as its DB_USER and execute the entire script.
-- 09_upgrade_existing_db.sql
-- DBeaver: execute this file as a script (Alt+X) on an existing database.
-- It upgrades a database created before question images and the current
-- reference-data set were added. The script is safe to run more than once.

DECLARE
    FUNCTION next_free_id(
        p_table_name IN VARCHAR2,
        p_column_name IN VARCHAR2,
        p_preferred_id IN NUMBER
    ) RETURN NUMBER IS
        v_count NUMBER;
        v_next_id NUMBER;
    BEGIN
        EXECUTE IMMEDIATE
            'SELECT COUNT(*) FROM ' || p_table_name || ' WHERE ' || p_column_name || ' = :id'
            INTO v_count
            USING p_preferred_id;

        IF v_count = 0 THEN
            RETURN p_preferred_id;
        END IF;

        EXECUTE IMMEDIATE
            'SELECT NVL(MAX(' || p_column_name || '), 0) + 1 FROM ' || p_table_name
            INTO v_next_id;

        RETURN v_next_id;
    END;

    PROCEDURE recreate_sequence(
        p_sequence_name IN VARCHAR2,
        p_table_name IN VARCHAR2,
        p_column_name IN VARCHAR2,
        p_min_start IN NUMBER
    ) IS
        v_start_with NUMBER;
    BEGIN
        EXECUTE IMMEDIATE
            'SELECT GREATEST(NVL(MAX(' || p_column_name || '), 0) + 1, :min_start) FROM ' || p_table_name
            INTO v_start_with
            USING p_min_start;

        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE ' || p_sequence_name;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2289 THEN
                    RAISE;
                END IF;
        END;

        EXECUTE IMMEDIATE
            'CREATE SEQUENCE ' || p_sequence_name || ' START WITH ' || v_start_with || ' INCREMENT BY 1';
    END;

    PROCEDURE ensure_role(
        p_id_role IN NUMBER,
        p_role_name IN VARCHAR2,
        p_role_description IN VARCHAR2
    ) IS
        v_count NUMBER;
        v_new_id NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM role WHERE role_name = p_role_name;

        IF v_count > 0 THEN
            UPDATE role
               SET role_description = p_role_description
             WHERE role_name = p_role_name;
        ELSE
            v_new_id := next_free_id('role', 'id_role', p_id_role);
            INSERT INTO role (id_role, role_name, role_description)
            VALUES (v_new_id, p_role_name, p_role_description);
        END IF;
    END;

    PROCEDURE ensure_difficulty_level(
        p_id_level IN NUMBER,
        p_level_name IN VARCHAR2
    ) IS
        v_count NUMBER;
        v_new_id NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM difficulty_level WHERE level_name = p_level_name;

        IF v_count = 0 THEN
            v_new_id := next_free_id('difficulty_level', 'id_level', p_id_level);
            INSERT INTO difficulty_level (id_level, level_name)
            VALUES (v_new_id, p_level_name);
        END IF;
    END;

    PROCEDURE ensure_question_type(
        p_type_id IN NUMBER,
        p_type_code IN VARCHAR2,
        p_type_name IN VARCHAR2,
        p_uses_options IN NUMBER,
        p_is_multi_select IN NUMBER,
        p_is_numeric_answer IN NUMBER,
        p_is_text_answer IN NUMBER
    ) IS
        v_count NUMBER;
        v_type_id question_type.type_id%TYPE;
        v_name_conflicts NUMBER;
        v_new_id NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM question_type WHERE type_code = p_type_code;

        IF v_count > 0 THEN
            SELECT type_id INTO v_type_id FROM question_type WHERE type_code = p_type_code;
            SELECT COUNT(*)
              INTO v_name_conflicts
              FROM question_type
             WHERE type_name = p_type_name
               AND type_id <> v_type_id;

            UPDATE question_type
               SET type_name = CASE WHEN v_name_conflicts = 0 THEN p_type_name ELSE type_name END,
                   uses_options = p_uses_options,
                   is_multi_select = p_is_multi_select,
                   is_numeric_answer = p_is_numeric_answer,
                   is_text_answer = p_is_text_answer
             WHERE type_code = p_type_code;
        ELSE
            SELECT COUNT(*) INTO v_count FROM question_type WHERE type_name = p_type_name;

            IF v_count > 0 THEN
                UPDATE question_type
                   SET type_code = p_type_code,
                       uses_options = p_uses_options,
                       is_multi_select = p_is_multi_select,
                       is_numeric_answer = p_is_numeric_answer,
                       is_text_answer = p_is_text_answer
                 WHERE type_name = p_type_name;
            ELSE
                v_new_id := next_free_id('question_type', 'type_id', p_type_id);
                INSERT INTO question_type (
                    type_id, type_code, type_name, uses_options,
                    is_multi_select, is_numeric_answer, is_text_answer
                ) VALUES (
                    v_new_id,
                    p_type_code, p_type_name, p_uses_options,
                    p_is_multi_select, p_is_numeric_answer, p_is_text_answer
                );
            END IF;
        END IF;
    END;
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE question ADD image_path VARCHAR2(255 CHAR)';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1430 THEN
                RAISE;
            END IF;
    END;

    ensure_role(1, 'USER', 'Обычный пользователь');
    ensure_role(2, 'AUTHOR', 'Автор тестов');
    ensure_role(3, 'ADMIN', 'Администратор');

    ensure_difficulty_level(1, 'Легкий');
    ensure_difficulty_level(2, 'Средний');
    ensure_difficulty_level(3, 'Сложный');

    ensure_question_type(1, 'SINGLE_CHOICE', 'Один правильный ответ', 1, 0, 0, 0);
    ensure_question_type(2, 'MULTIPLE_CHOICE', 'Несколько правильных ответов', 1, 1, 0, 0);
    ensure_question_type(3, 'TEXT', 'Текстовый ответ', 0, 0, 0, 1);
    ensure_question_type(4, 'NUMBER', 'Числовой ответ', 0, 0, 1, 0);
    ensure_question_type(5, 'TRUE_FALSE', 'Верно / неверно', 1, 0, 0, 0);
    ensure_question_type(6, 'SHORT_TEXT', 'Короткий ответ', 0, 0, 0, 1);

    MERGE INTO attempt_status s
    USING (
        SELECT 'STARTED' status_code, 'Начата' status_name, 0 is_terminal, 0 is_successful FROM dual UNION ALL
        SELECT 'FINISHED', 'Завершена', 1, 1 FROM dual UNION ALL
        SELECT 'TIME_EXPIRED', 'Время истекло', 1, 1 FROM dual UNION ALL
        SELECT 'INTERRUPTED', 'Прервана', 1, 0 FROM dual
    ) src
    ON (s.status_code = src.status_code)
    WHEN MATCHED THEN UPDATE SET
        s.status_name = src.status_name,
        s.is_terminal = src.is_terminal,
        s.is_successful = src.is_successful
    WHEN NOT MATCHED THEN INSERT (status_code, status_name, is_terminal, is_successful)
    VALUES (src.status_code, src.status_name, src.is_terminal, src.is_successful);

    recreate_sequence('seq_role', 'role', 'id_role', 4);
    recreate_sequence('seq_difficulty_level', 'difficulty_level', 'id_level', 4);
    recreate_sequence('seq_question_type', 'question_type', 'type_id', 7);

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Existing database upgraded.');
    DBMS_OUTPUT.PUT_LINE('Next step: execute sql/05_package_body.sql as a script to recompile quiz_platform.');
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[CREATE TABLE attempt_question_visit (id_attempt NUMBER NOT NULL REFERENCES attempt(id_attempt),
    id_qt NUMBER NOT NULL REFERENCES question_in_test(id_qt),
    started_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_attempt_question_visit PRIMARY KEY (id_attempt, id_qt)
)]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 04_package_spec.sql
CREATE OR REPLACE PACKAGE quiz_platform AS
    PROCEDURE info;
    FUNCTION touch_question(p_id_attempt NUMBER, p_id_qt NUMBER, p_uid NUMBER) RETURN NUMBER;
    PROCEDURE delete_answer_option(p_id_question NUMBER, p_id_option NUMBER, p_uid_author NUMBER);
    PROCEDURE remove_test_question(p_uid_author NUMBER, p_id_test NUMBER, p_id_question NUMBER);
    PROCEDURE set_user_role(p_uid_admin NUMBER, p_uid NUMBER, p_role_code VARCHAR2);
    PROCEDURE register_user(p_user_name VARCHAR2, p_password VARCHAR2);
    FUNCTION register_user_id(p_user_name VARCHAR2, p_password VARCHAR2) RETURN NUMBER;
    FUNCTION login_user(p_uid NUMBER, p_password VARCHAR2) RETURN NUMBER;
    FUNCTION check_author_role(p_uid NUMBER) RETURN NUMBER;
    FUNCTION check_admin_role(p_uid NUMBER) RETURN NUMBER;
    FUNCTION get_user(p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_categories RETURN SYS_REFCURSOR;
    FUNCTION list_difficulty_levels RETURN SYS_REFCURSOR;
    FUNCTION list_question_types RETURN SYS_REFCURSOR;
    PROCEDURE create_test(p_uid_author NUMBER, p_test_name VARCHAR2, p_test_description VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_time_limit NUMBER, p_attempt_limit NUMBER, p_show_feedback NUMBER, p_question_count NUMBER);
    FUNCTION create_test_id(p_uid_author NUMBER, p_test_name VARCHAR2, p_test_description VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_time_limit NUMBER, p_attempt_limit NUMBER, p_show_feedback NUMBER, p_question_count NUMBER) RETURN NUMBER;
    PROCEDURE publish_test(p_uid_author NUMBER, p_id_test NUMBER, p_direct_call NUMBER DEFAULT 1);
    PROCEDURE generate_test_questions(p_uid_author NUMBER, p_id_test NUMBER);
    PROCEDURE add_question(p_uid_author NUMBER, p_question_text VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_type_id NUMBER, p_correct_text VARCHAR2, p_correct_number NUMBER, p_tolerance NUMBER, p_explanation VARCHAR2);
    FUNCTION add_question_id(p_uid_author NUMBER, p_question_text VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_type_id NUMBER, p_correct_text VARCHAR2, p_correct_number NUMBER, p_tolerance NUMBER, p_explanation VARCHAR2) RETURN NUMBER;
    PROCEDURE add_answer_option(p_id_question NUMBER, p_option_text VARCHAR2, p_is_correct NUMBER);
    PROCEDURE add_question_type(p_type_name VARCHAR2);
    PROCEDURE add_category(p_category_name VARCHAR2, p_category_description VARCHAR2);
    PROCEDURE add_difficulty_level(p_level_name VARCHAR2);
    PROCEDURE deactivate_question(p_id_question NUMBER, p_uid_author NUMBER);
    PROCEDURE include_question_in_test(p_uid_author NUMBER, p_id_test NUMBER, p_id_question NUMBER, p_weight NUMBER, p_order_num NUMBER, p_is_required NUMBER, p_time_limit NUMBER);
    PROCEDURE grant_test_access(p_uid_author NUMBER, p_id_test NUMBER, p_uid NUMBER);
    PROCEDURE deactivate_test_access(p_id_test NUMBER, p_uid NUMBER, p_uid_author NUMBER);
    FUNCTION check_access(p_id_test NUMBER, p_uid NUMBER) RETURN NUMBER;
    PROCEDURE start_attempt(p_id_test NUMBER, p_uid NUMBER);
    FUNCTION start_attempt_id(p_id_test NUMBER, p_uid NUMBER) RETURN NUMBER;
    PROCEDURE save_answer(p_id_attempt NUMBER, p_id_qt NUMBER, p_answer_text VARCHAR2, p_answer_number NUMBER, p_answer_time NUMBER, p_uid NUMBER);
    FUNCTION save_answer_id(p_id_attempt NUMBER, p_id_qt NUMBER, p_answer_text VARCHAR2, p_answer_number NUMBER, p_answer_time NUMBER, p_uid NUMBER) RETURN NUMBER;
    PROCEDURE save_selected_option(p_id_answer NUMBER, p_id_option NUMBER);
    FUNCTION check_answer(p_id_answer NUMBER) RETURN NUMBER;
    FUNCTION calc_answer_score(p_id_answer NUMBER) RETURN NUMBER;
    PROCEDURE finish_attempt(p_id_attempt NUMBER, p_uid NUMBER);
    PROCEDURE calc_result(p_id_attempt NUMBER);
    FUNCTION list_author_questions(p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_author_question(p_id_question NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_answer_options(p_id_question NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_available_tests(p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_available_test(p_id_test NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_attempt(p_id_attempt NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_questions(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_answers(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_selected_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_attempt_question_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_attempt_result(p_id_attempt NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_result_answers(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_result_selected_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_result_correct_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_user_attempts(p_uid NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_author_tests(p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_author_test(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_test_questions(p_id_test NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_selected_test_questions(p_id_test NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_question_pool(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_author_test_access_header(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_test_access(p_id_test NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_test_statistics_summary(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_test_statistics_questions(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_users(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_attempts(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_tests(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION list_admin_questions(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    FUNCTION get_admin_statistics(p_uid_admin NUMBER) RETURN SYS_REFCURSOR;
    PROCEDURE show_result(p_id_attempt NUMBER);
    PROCEDURE show_user_attempts(p_uid NUMBER);
    PROCEDURE show_test_statistics(p_id_test NUMBER);
END quiz_platform;
/

-- 05_package_body.sql
CREATE OR REPLACE PACKAGE BODY quiz_platform AS
    PROCEDURE info IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('quiz_platform package loaded');
    END;

    FUNCTION has_role(p_uid NUMBER, p_role_name VARCHAR2) RETURN NUMBER IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_cnt
        FROM users u
        JOIN role r ON r.id_role = u.id_role
        WHERE u.user_id = p_uid
          AND u.is_active = 1
          AND r.role_name = p_role_name;

        IF v_cnt > 0 THEN
            RETURN 1;
        END IF;
        RETURN 0;
    END;

    PROCEDURE require_author(p_uid NUMBER) IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_cnt
        FROM users u
        JOIN role r ON r.id_role = u.id_role
        WHERE u.user_id = p_uid
          AND u.is_active = 1
          AND r.role_name IN ('AUTHOR', 'ADMIN');

        IF v_cnt = 0 THEN
            RAISE_APPLICATION_ERROR(-20030, 'Доступ разрешен только автору или администратору');
        END IF;
    END;

    FUNCTION check_author_role(p_uid NUMBER) RETURN NUMBER IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_cnt
        FROM users u
        JOIN role r ON r.id_role = u.id_role
        WHERE u.user_id = p_uid
          AND u.is_active = 1
          AND r.role_name IN ('AUTHOR', 'ADMIN');

        IF v_cnt > 0 THEN
            RETURN 1;
        END IF;
        RETURN 0;
    END;

    FUNCTION check_admin_role(p_uid NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN has_role(p_uid, 'ADMIN');
    END;

    PROCEDURE require_admin(p_uid NUMBER) IS
    BEGIN
        IF check_admin_role(p_uid) <> 1 THEN
            RAISE_APPLICATION_ERROR(-20031, 'Доступ разрешен только администратору');
        END IF;
    END;

    PROCEDURE require_editable_test(p_uid NUMBER, p_id_test NUMBER) IS
        v_active NUMBER;
        v_count NUMBER;
    BEGIN
        require_author(p_uid);
        SELECT is_active INTO v_active FROM test
        WHERE id_test = p_id_test AND (uid_author = p_uid OR check_admin_role(p_uid) = 1) FOR UPDATE;
        SELECT COUNT(*) INTO v_count FROM attempt WHERE id_test = p_id_test;
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20120, 'Тест уже проходили. Для изменения состава создайте новый тест.');
        END IF;
        IF v_active = 1 THEN
            RAISE_APPLICATION_ERROR(-20121, 'Сначала скройте тест, чтобы изменить его вопросы.');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20105, 'Тест не найден');
    END;

    PROCEDURE require_editable_question(p_id_question NUMBER) IS
        v_id NUMBER;
        v_count NUMBER;
    BEGIN
        SELECT id_question INTO v_id FROM question WHERE id_question = p_id_question FOR UPDATE;
        SELECT COUNT(*) INTO v_count
        FROM question_in_test qt JOIN test t ON t.id_test = qt.id_test
        WHERE qt.id_question = p_id_question
          AND (t.is_active = 1 OR EXISTS (SELECT 1 FROM attempt a WHERE a.id_test = t.id_test));
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20122, 'Вопрос используется в опубликованном или уже пройденном тесте. Создайте новый вопрос.');
        END IF;
    END;

    FUNCTION question_ready(p_id_question NUMBER) RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM question q
        JOIN question_type ty ON ty.type_id = q.type_id
        WHERE q.id_question = p_id_question AND q.is_active = 1
          AND ((ty.is_numeric_answer = 1 AND q.correct_number IS NOT NULL)
            OR (ty.is_text_answer = 1 AND TRIM(q.correct_text) IS NOT NULL)
            OR (ty.uses_options = 1
                AND (SELECT COUNT(*) FROM answer_option o WHERE o.id_question = q.id_question) >= 2
                AND ((ty.is_multi_select = 0 AND (SELECT COUNT(*) FROM answer_option o WHERE o.id_question = q.id_question AND o.is_correct = 1) = 1)
                  OR (ty.is_multi_select = 1 AND (SELECT COUNT(*) FROM answer_option o WHERE o.id_question = q.id_question AND o.is_correct = 1) >= 1))));
        RETURN v_count;
    END;

    PROCEDURE set_user_role(p_uid_admin NUMBER, p_uid NUMBER, p_role_code VARCHAR2) IS
        v_role NUMBER;
    BEGIN
        require_admin(p_uid_admin);
        IF p_uid_admin = p_uid AND p_role_code <> 'ADMIN' THEN
            RAISE_APPLICATION_ERROR(-20032, 'Нельзя снять роль администратора у самого себя.');
        END IF;
        SELECT id_role INTO v_role FROM role WHERE role_name = p_role_code;
        UPDATE users SET id_role = v_role WHERE user_id = p_uid;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20033, 'Пользователь не найден.');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20034, 'Неизвестная роль.');
    END;

    PROCEDURE delete_answer_option(p_id_question NUMBER, p_id_option NUMBER, p_uid_author NUMBER) IS
        v_count NUMBER;
    BEGIN
        require_author(p_uid_author);
        SELECT COUNT(*) INTO v_count FROM question WHERE id_question = p_id_question AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        IF v_count = 0 THEN RAISE_APPLICATION_ERROR(-20025, 'Вопрос не найден.'); END IF;
        require_editable_question(p_id_question);
        DELETE FROM answer_option WHERE id_question = p_id_question AND id_option = p_id_option;
    END;

    PROCEDURE remove_test_question(p_uid_author NUMBER, p_id_test NUMBER, p_id_question NUMBER) IS
    BEGIN
        require_editable_test(p_uid_author, p_id_test);
        DELETE FROM question_in_test WHERE id_test = p_id_test AND id_question = p_id_question;
    END;

    FUNCTION is_terminal_attempt_status(p_status VARCHAR2) RETURN NUMBER IS
        v_terminal NUMBER;
    BEGIN
        SELECT is_terminal
        INTO v_terminal
        FROM attempt_status
        WHERE status_code = p_status;
        RETURN v_terminal;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END;

    PROCEDURE register_user(p_user_name VARCHAR2, p_password VARCHAR2) IS
        v_user_id users.user_id%TYPE;
    BEGIN
        v_user_id := register_user_id(p_user_name, p_password);
    END;

    FUNCTION register_user_id(p_user_name VARCHAR2, p_password VARCHAR2) RETURN NUMBER IS
        v_password_hash users.password_hash%TYPE;
        v_user_id users.user_id%TYPE;
        v_role_id role.id_role%TYPE;
        v_count NUMBER;
    BEGIN
        IF p_user_name IS NULL OR LENGTH(TRIM(p_user_name)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20010, 'Имя пользователя не может быть пустым');
        END IF;
        IF p_password IS NULL OR LENGTH(p_password) < 4 THEN
            RAISE_APPLICATION_ERROR(-20011, 'Пароль слишком короткий');
        END IF;

        SELECT STANDARD_HASH(p_password, 'SHA256') INTO v_password_hash FROM dual;
        SELECT id_role INTO v_role_id FROM role WHERE role_name = 'USER' FOR UPDATE;
        SELECT COUNT(*) INTO v_count FROM users;
        IF v_count = 0 THEN
            SELECT id_role INTO v_role_id FROM role WHERE role_name = 'ADMIN';
        END IF;

        INSERT INTO users (id_role, password_hash, user_name, created_at, is_active)
        VALUES (v_role_id, v_password_hash, TRIM(p_user_name), SYSDATE, 1)
        RETURNING user_id INTO v_user_id;

        RETURN v_user_id;
    END;

    FUNCTION login_user(p_uid NUMBER, p_password VARCHAR2) RETURN NUMBER IS
        v_role_id users.id_role%TYPE;
        v_hash users.password_hash%TYPE;
        v_password_hash users.password_hash%TYPE;
        v_active users.is_active%TYPE;
    BEGIN
        BEGIN
            SELECT id_role, password_hash, is_active
            INTO v_role_id, v_hash, v_active
            FROM users
            WHERE user_id = p_uid;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20001, 'Неверный user_id');
        END;

        IF v_active <> 1 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Пользователь неактивен');
        END IF;

        SELECT STANDARD_HASH(p_password, 'SHA256') INTO v_password_hash FROM dual;

        IF p_password IS NULL OR v_password_hash IS NULL OR v_hash <> v_password_hash THEN
            RAISE_APPLICATION_ERROR(-20003, 'Неверный пароль');
        END IF;

        RETURN v_role_id;
    END;

    PROCEDURE create_test(
        p_uid_author NUMBER,
        p_test_name VARCHAR2,
        p_test_description VARCHAR2,
        p_id_category NUMBER,
        p_id_level NUMBER,
        p_time_limit NUMBER,
        p_attempt_limit NUMBER,
        p_show_feedback NUMBER,
        p_question_count NUMBER
    ) IS
        v_test_id test.id_test%TYPE;
    BEGIN
        v_test_id := create_test_id(
            p_uid_author, p_test_name, p_test_description, p_id_category, p_id_level,
            p_time_limit, p_attempt_limit, p_show_feedback, p_question_count
        );
    END;

    FUNCTION create_test_id(
        p_uid_author NUMBER,
        p_test_name VARCHAR2,
        p_test_description VARCHAR2,
        p_id_category NUMBER,
        p_id_level NUMBER,
        p_time_limit NUMBER,
        p_attempt_limit NUMBER,
        p_show_feedback NUMBER,
        p_question_count NUMBER
    ) RETURN NUMBER IS
        v_test_id test.id_test%TYPE;
    BEGIN
        IF p_test_name IS NULL OR LENGTH(TRIM(p_test_name)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20100, 'Название теста обязательно');
        END IF;
        IF p_attempt_limit IS NULL OR p_attempt_limit <= 0 THEN
            RAISE_APPLICATION_ERROR(-20101, 'Лимит попыток должен быть больше 0');
        END IF;
        IF p_show_feedback NOT IN (0, 1) THEN
            RAISE_APPLICATION_ERROR(-20102, 'show_feedback должен быть 0 или 1');
        END IF;

        require_author(p_uid_author);

        INSERT INTO test (
            uid_author, id_category, id_level, test_name, test_description,
            created_at, time_limit, attempt_limit, question_count, show_feedback, is_active
        ) VALUES (
            p_uid_author, p_id_category, p_id_level, TRIM(p_test_name), p_test_description,
            SYSDATE, p_time_limit, p_attempt_limit, p_question_count, p_show_feedback, 0
        )
        RETURNING id_test INTO v_test_id;

        RETURN v_test_id;
    END;

    PROCEDURE publish_test(p_uid_author NUMBER, p_id_test NUMBER, p_direct_call NUMBER DEFAULT 1) IS
        v_active NUMBER;
        v_q_count NUMBER;
    BEGIN
        require_author(p_uid_author);

        SELECT is_active
        INTO v_active
        FROM test
        WHERE id_test = p_id_test
          AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1) FOR UPDATE;
        SELECT COUNT(*) INTO v_q_count FROM question_in_test WHERE id_test = p_id_test;

        IF v_active = 0 THEN
            IF v_q_count = 0 THEN
                RAISE_APPLICATION_ERROR(-20104, 'Нельзя опубликовать тест без вопросов');
            END IF;
            FOR q IN (SELECT id_question FROM question_in_test WHERE id_test = p_id_test) LOOP
                IF question_ready(q.id_question) <> 1 THEN
                    RAISE_APPLICATION_ERROR(-20123, 'Вопрос #' || q.id_question || ': проверьте активность, эталон и варианты (минимум два, с правильным ответом).');
                END IF;
            END LOOP;
            UPDATE test SET is_active = 1 WHERE id_test = p_id_test;
        ELSE
            IF p_direct_call = 1 THEN
                UPDATE test SET is_active = 0 WHERE id_test = p_id_test;
            END IF;
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20105, 'Тест не найден');
    END;

    PROCEDURE include_question_in_test(
        p_uid_author NUMBER,
        p_id_test NUMBER,
        p_id_question NUMBER,
        p_weight NUMBER,
        p_order_num NUMBER,
        p_is_required NUMBER,
        p_time_limit NUMBER
    ) IS
        v_question_active NUMBER;
        v_test_exists NUMBER;
    BEGIN
        require_editable_test(p_uid_author, p_id_test);

        IF p_is_required NOT IN (0, 1) THEN
            RAISE_APPLICATION_ERROR(-20106, 'is_required должен быть 0 или 1');
        END IF;

        SELECT COUNT(*)
        INTO v_test_exists
        FROM test
        WHERE id_test = p_id_test
          AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        IF v_test_exists = 0 THEN
            RAISE_APPLICATION_ERROR(-20105, 'Тест не найден');
        END IF;

        SELECT is_active
        INTO v_question_active
        FROM question
        WHERE id_question = p_id_question
          AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        IF v_question_active <> 1 THEN
            RAISE_APPLICATION_ERROR(-20107, 'Нельзя добавить неактивный вопрос');
        END IF;

        INSERT INTO question_in_test (id_test, id_question, weight, order_num, is_required, time_limit)
        VALUES (p_id_test, p_id_question, NVL(p_weight, 1), p_order_num, p_is_required, p_time_limit);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20108, 'Вопрос не найден');
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20109, 'Вопрос уже добавлен или занят порядок вопроса');
    END;

    PROCEDURE generate_test_questions(p_uid_author NUMBER, p_id_test NUMBER) IS
        v_id_level test.id_level%TYPE;
        v_question_count test.question_count%TYPE;
        v_id_category test.id_category%TYPE;
        v_exists NUMBER;
        v_order NUMBER := 1;
    BEGIN
        require_editable_test(p_uid_author, p_id_test);

        SELECT id_level, question_count, id_category
        INTO v_id_level, v_question_count, v_id_category
        FROM test
        WHERE id_test = p_id_test
          AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);

        IF v_id_level IS NULL OR v_question_count IS NULL OR v_question_count <= 0 THEN
            RAISE_APPLICATION_ERROR(-20110, 'Для автогенерации заполните сложность и количество вопросов');
        END IF;

        v_exists := 0;
        FOR q IN (SELECT id_question FROM question WHERE (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
                  AND is_active = 1 AND id_level = v_id_level
                  AND (v_id_category IS NULL OR id_category = v_id_category)) LOOP
            IF question_ready(q.id_question) = 1 THEN v_exists := v_exists + 1; END IF;
        END LOOP;
        IF v_exists < v_question_count THEN
            RAISE_APPLICATION_ERROR(-20111, 'Недостаточно готовых вопросов автора для выбранной категории и сложности.');
        END IF;
        DELETE FROM question_in_test WHERE id_test = p_id_test;

        FOR rec IN (
            SELECT id_question
            FROM (
                SELECT q.id_question
                FROM question q
                WHERE q.is_active = 1
                  AND q.id_level = v_id_level
                  AND (q.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
                  AND (v_id_category IS NULL OR q.id_category = v_id_category)
                ORDER BY DBMS_RANDOM.VALUE
            )
        ) LOOP
            IF question_ready(rec.id_question) = 0 THEN CONTINUE; END IF;
            EXIT WHEN v_order > v_question_count;
            INSERT INTO question_in_test (id_test, id_question, weight, order_num, is_required, time_limit)
            VALUES (p_id_test, rec.id_question, 1, v_order, 1, NULL);
            v_order := v_order + 1;
        END LOOP;

        SELECT COUNT(*) INTO v_exists FROM question_in_test WHERE id_test = p_id_test;
        IF v_exists < v_question_count THEN
            RAISE_APPLICATION_ERROR(-20111, 'Недостаточно вопросов для генерации');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20105, 'Тест не найден');
    END;

    PROCEDURE add_question_type(p_type_name VARCHAR2) IS
    BEGIN
        IF p_type_name IS NULL OR LENGTH(TRIM(p_type_name)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20020, 'Название типа вопроса не может быть пустым');
        END IF;
        INSERT INTO question_type (type_code, type_name, uses_options, is_multi_select, is_numeric_answer, is_text_answer)
        VALUES (SUBSTR(UPPER(REPLACE(TRIM(p_type_name), ' ', '_')), 1, 30), TRIM(p_type_name), 0, 0, 0, 1);
    END;

    PROCEDURE add_category(p_category_name VARCHAR2, p_category_description VARCHAR2) IS
    BEGIN
        IF p_category_name IS NULL OR LENGTH(TRIM(p_category_name)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20026, 'Название категории не может быть пустым');
        END IF;

        INSERT INTO category (category_name, category_description)
        VALUES (TRIM(p_category_name), p_category_description);
    END;

    PROCEDURE add_difficulty_level(p_level_name VARCHAR2) IS
    BEGIN
        IF p_level_name IS NULL OR LENGTH(TRIM(p_level_name)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20027, 'Название уровня сложности не может быть пустым');
        END IF;

        INSERT INTO difficulty_level (level_name)
        VALUES (TRIM(p_level_name));
    END;

    PROCEDURE add_question(p_uid_author NUMBER, p_question_text VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_type_id NUMBER, p_correct_text VARCHAR2, p_correct_number NUMBER, p_tolerance NUMBER, p_explanation VARCHAR2) IS
        v_question_id question.id_question%TYPE;
    BEGIN
        v_question_id := add_question_id(
            p_uid_author, p_question_text, p_id_category, p_id_level, p_type_id,
            p_correct_text, p_correct_number, p_tolerance, p_explanation
        );
    END;

    FUNCTION add_question_id(p_uid_author NUMBER, p_question_text VARCHAR2, p_id_category NUMBER, p_id_level NUMBER, p_type_id NUMBER, p_correct_text VARCHAR2, p_correct_number NUMBER, p_tolerance NUMBER, p_explanation VARCHAR2) RETURN NUMBER IS
        v_question_id question.id_question%TYPE;
        v_numeric NUMBER;
        v_text NUMBER;
    BEGIN
        IF p_question_text IS NULL OR LENGTH(TRIM(p_question_text)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20021, 'Текст вопроса не может быть пустым');
        END IF;
        require_author(p_uid_author);

        SELECT is_numeric_answer, is_text_answer INTO v_numeric, v_text FROM question_type WHERE type_id = p_type_id;
        IF v_numeric = 1 AND p_correct_number IS NULL THEN
            RAISE_APPLICATION_ERROR(-20035, 'Для числового вопроса укажите правильное число.');
        END IF;
        IF v_text = 1 AND TRIM(p_correct_text) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20036, 'Для текстового вопроса укажите правильный ответ.');
        END IF;

        INSERT INTO question (uid_author, id_category, id_level, type_id, question_text, explanation, correct_text, correct_number, tolerance, created_at, is_active)
        VALUES (p_uid_author, p_id_category, p_id_level, p_type_id, TRIM(p_question_text), p_explanation, p_correct_text, p_correct_number, p_tolerance, SYSDATE, 1)
        RETURNING id_question INTO v_question_id;

        RETURN v_question_id;
    END;

    PROCEDURE add_answer_option(p_id_question NUMBER, p_option_text VARCHAR2, p_is_correct NUMBER) IS
        v_question_cnt NUMBER;
        v_options NUMBER;
        v_multi NUMBER;
    BEGIN
        IF p_option_text IS NULL OR LENGTH(TRIM(p_option_text)) = 0 THEN
            RAISE_APPLICATION_ERROR(-20023, 'Текст варианта не может быть пустым');
        END IF;
        IF p_is_correct NOT IN (0, 1) THEN
            RAISE_APPLICATION_ERROR(-20024, 'Признак правильности должен быть 0 или 1');
        END IF;

        require_editable_question(p_id_question);
        SELECT ty.uses_options, ty.is_multi_select INTO v_options, v_multi
        FROM question q JOIN question_type ty ON ty.type_id = q.type_id WHERE q.id_question = p_id_question;
        IF v_options = 0 THEN RAISE_APPLICATION_ERROR(-20037, 'Этот тип вопроса не использует варианты.'); END IF;
        SELECT COUNT(*) INTO v_question_cnt FROM answer_option WHERE id_question = p_id_question AND is_correct = 1;
        IF p_is_correct = 1 AND v_multi = 0 AND v_question_cnt > 0 THEN
            RAISE_APPLICATION_ERROR(-20038, 'Для этого типа допустим только один правильный вариант. Сначала удалите ошибочный.');
        END IF;
        SELECT COUNT(*) INTO v_question_cnt FROM question WHERE id_question = p_id_question;
        IF v_question_cnt = 0 THEN
            RAISE_APPLICATION_ERROR(-20025, 'Вопрос не найден');
        END IF;

        INSERT INTO answer_option (id_question, option_text, is_correct)
        VALUES (p_id_question, TRIM(p_option_text), p_is_correct);
    END;

    PROCEDURE deactivate_question(p_id_question NUMBER, p_uid_author NUMBER) IS
    BEGIN
        require_author(p_uid_author);

        UPDATE question
        SET is_active = 0
        WHERE id_question = p_id_question
          AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20028, 'Вопрос не найден');
        END IF;
    END;

    PROCEDURE grant_test_access(p_uid_author NUMBER, p_id_test NUMBER, p_uid NUMBER) IS
        v_user_cnt NUMBER;
        v_test_cnt NUMBER;
    BEGIN
        require_author(p_uid_author);

        SELECT COUNT(*) INTO v_user_cnt FROM users WHERE user_id = p_uid AND is_active = 1;
        IF v_user_cnt = 0 THEN
            RAISE_APPLICATION_ERROR(-20200, 'Пользователь не найден или неактивен');
        END IF;

        SELECT COUNT(*)
        INTO v_test_cnt
        FROM test
        WHERE id_test = p_id_test
          AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        IF v_test_cnt = 0 THEN
            RAISE_APPLICATION_ERROR(-20201, 'Тест не найден');
        END IF;

        MERGE INTO test_access ta
        USING (SELECT p_uid user_id, p_id_test id_test FROM dual) src
        ON (ta.user_id = src.user_id AND ta.id_test = src.id_test)
        WHEN MATCHED THEN
            UPDATE SET ta.is_active = 1, ta.granted_at = SYSDATE
        WHEN NOT MATCHED THEN
            INSERT (user_id, id_test, granted_at, is_active)
            VALUES (src.user_id, src.id_test, SYSDATE, 1);
    END;

    PROCEDURE deactivate_test_access(p_id_test NUMBER, p_uid NUMBER, p_uid_author NUMBER) IS
    BEGIN
        require_author(p_uid_author);

        UPDATE test_access ta
        SET ta.is_active = 0
        WHERE ta.id_test = p_id_test
          AND ta.user_id = p_uid
          AND EXISTS (
            SELECT 1
            FROM test t
            WHERE t.id_test = ta.id_test
              AND (t.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
          );

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20202, 'Доступ к тесту не найден');
        END IF;
    END;

    FUNCTION check_access(p_id_test NUMBER, p_uid NUMBER) RETURN NUMBER IS
        v_cnt NUMBER;
    BEGIN
        IF check_admin_role(p_uid) = 1 THEN
            SELECT COUNT(*) INTO v_cnt FROM test WHERE id_test = p_id_test;
            RETURN v_cnt;
        END IF;
        SELECT COUNT(*)
        INTO v_cnt
        FROM test_access ta
        JOIN test t ON t.id_test = ta.id_test
        JOIN users u ON u.user_id = ta.user_id
        WHERE ta.id_test = p_id_test
          AND ta.user_id = p_uid
          AND ta.is_active = 1
          AND t.is_active = 1
          AND u.is_active = 1;

        IF v_cnt > 0 THEN
            RETURN 1;
        END IF;
        RETURN 0;
    END;
    PROCEDURE start_attempt(p_id_test NUMBER, p_uid NUMBER) IS
        v_attempt_id attempt.id_attempt%TYPE;
    BEGIN
        v_attempt_id := start_attempt_id(p_id_test, p_uid);
    END;

    FUNCTION start_attempt_id(p_id_test NUMBER, p_uid NUMBER) RETURN NUMBER IS
        v_user_active NUMBER;
        v_test_active NUMBER;
        v_access NUMBER;
        v_attempt_limit NUMBER;
        v_attempts_used NUMBER;
        v_attempt_no NUMBER;
        v_attempt_id attempt.id_attempt%TYPE;
    BEGIN
        SELECT is_active INTO v_user_active FROM users WHERE user_id = p_uid FOR UPDATE;
        IF v_user_active <> 1 THEN
            RAISE_APPLICATION_ERROR(-20300, 'Пользователь неактивен');
        END IF;

        SELECT is_active, attempt_limit
        INTO v_test_active, v_attempt_limit
        FROM test
        WHERE id_test = p_id_test FOR UPDATE;
        IF v_test_active <> 1 AND check_admin_role(p_uid) <> 1 THEN
            RAISE_APPLICATION_ERROR(-20301, 'Тест скрыт');
        END IF;

        v_access := check_access(p_id_test, p_uid);
        IF v_access <> 1 THEN
            RAISE_APPLICATION_ERROR(-20302, 'Нет доступа к тесту');
        END IF;

        SELECT MIN(id_attempt) INTO v_attempt_id FROM attempt
        WHERE user_id = p_uid AND id_test = p_id_test AND status = 'STARTED';
        IF v_attempt_id IS NOT NULL THEN RETURN v_attempt_id; END IF;
        SELECT COUNT(*) INTO v_attempts_used FROM question_in_test WHERE id_test = p_id_test;
        IF v_attempts_used = 0 THEN RAISE_APPLICATION_ERROR(-20104, 'В тесте нет вопросов.'); END IF;
        IF v_test_active = 0 THEN
            FOR q IN (SELECT id_question FROM question_in_test WHERE id_test = p_id_test) LOOP
                IF question_ready(q.id_question) <> 1 THEN
                    RAISE_APPLICATION_ERROR(-20123, 'Вопрос #' || q.id_question || ' ещё не готов к прохождению.');
                END IF;
            END LOOP;
        END IF;

        SELECT NVL(MAX(attempt_number), 0)
        INTO v_attempts_used
        FROM attempt
        WHERE user_id = p_uid AND id_test = p_id_test;
        IF v_attempts_used >= v_attempt_limit AND check_admin_role(p_uid) <> 1 THEN
            RAISE_APPLICATION_ERROR(-20303, 'Превышен лимит попыток');
        END IF;

        v_attempt_no := v_attempts_used + 1;
        INSERT INTO attempt (user_id, id_test, attempt_number, start_date, status, finished_in_time)
        VALUES (p_uid, p_id_test, v_attempt_no, SYSDATE, 'STARTED', 1)
        RETURNING id_attempt INTO v_attempt_id;

        RETURN v_attempt_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20304, 'Пользователь или тест не найден');
    END;

    PROCEDURE save_answer(
        p_id_attempt NUMBER,
        p_id_qt NUMBER,
        p_answer_text VARCHAR2,
        p_answer_number NUMBER,
        p_answer_time NUMBER,
        p_uid NUMBER
    ) IS
        v_answer_id answer.id_answer%TYPE;
    BEGIN
        v_answer_id := save_answer_id(p_id_attempt, p_id_qt, p_answer_text, p_answer_number, p_answer_time, p_uid);
    END;

    FUNCTION touch_question(p_id_attempt NUMBER, p_id_qt NUMBER, p_uid NUMBER) RETURN NUMBER IS
        v_status attempt.status%TYPE;
        v_test_id NUMBER;
        v_uid NUMBER;
        v_started DATE;
        v_count NUMBER;
    BEGIN
        SELECT status, id_test, user_id INTO v_status, v_test_id, v_uid
        FROM attempt WHERE id_attempt = p_id_attempt FOR UPDATE;
        IF v_uid <> p_uid AND check_admin_role(p_uid) <> 1 THEN RAISE_APPLICATION_ERROR(-20313, 'Попытка не принадлежит пользователю'); END IF;
        IF v_status <> 'STARTED' THEN RAISE_APPLICATION_ERROR(-20305, 'Попытка завершена'); END IF;
        SELECT COUNT(*) INTO v_count FROM question_in_test WHERE id_qt = p_id_qt AND id_test = v_test_id;
        IF v_count = 0 THEN RAISE_APPLICATION_ERROR(-20312, 'Вопрос не относится к данной попытке'); END IF;
        BEGIN
            SELECT started_at INTO v_started FROM attempt_question_visit
            WHERE id_attempt = p_id_attempt AND id_qt = p_id_qt;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                v_started := SYSDATE;
                INSERT INTO attempt_question_visit (id_attempt, id_qt, started_at) VALUES (p_id_attempt, p_id_qt, v_started);
        END;
        RETURN GREATEST(0, FLOOR((SYSDATE - v_started) * 86400));
    END;

    FUNCTION save_answer_id(
        p_id_attempt NUMBER,
        p_id_qt NUMBER,
        p_answer_text VARCHAR2,
        p_answer_number NUMBER,
        p_answer_time NUMBER,
        p_uid NUMBER
    ) RETURN NUMBER IS
        v_status attempt.status%TYPE;
        v_attempt_uid attempt.user_id%TYPE;
        v_test_id attempt.id_test%TYPE;
        v_started DATE;
        v_test_time_limit NUMBER;
        v_answer_id answer.id_answer%TYPE;
        v_qt_cnt NUMBER;
        v_elapsed NUMBER;
        v_required NUMBER;
        v_q_limit NUMBER;
        v_uses_options NUMBER;
        v_numeric NUMBER;
        v_text NUMBER;
    BEGIN
        SELECT a.status, a.user_id, a.id_test, a.start_date, t.time_limit
        INTO v_status, v_attempt_uid, v_test_id, v_started, v_test_time_limit
        FROM attempt a
        JOIN test t ON t.id_test = a.id_test
        WHERE a.id_attempt = p_id_attempt FOR UPDATE OF a.status;

        IF v_attempt_uid <> p_uid AND check_admin_role(p_uid) <> 1 THEN
            RAISE_APPLICATION_ERROR(-20313, 'Попытка не принадлежит пользователю');
        END IF;

        IF v_status <> 'STARTED' THEN
            RAISE_APPLICATION_ERROR(-20305, 'Попытка завершена');
        END IF;

        SELECT COUNT(*)
        INTO v_qt_cnt
        FROM question_in_test
        WHERE id_qt = p_id_qt
          AND id_test = v_test_id;

        IF v_qt_cnt = 0 THEN
            RAISE_APPLICATION_ERROR(-20312, 'Вопрос не относится к данной попытке');
        END IF;

        IF v_test_time_limit IS NOT NULL
           AND (SYSDATE - v_started) * 86400 >= v_test_time_limit THEN
            finish_attempt(p_id_attempt, p_uid);
            RETURN 0;
        END IF;

        SELECT MIN(id_answer) INTO v_answer_id FROM answer WHERE id_attempt = p_id_attempt AND id_qt = p_id_qt;
        IF v_answer_id IS NOT NULL THEN
            RAISE_APPLICATION_ERROR(-20307, 'Ответ уже сохранён. Перейдите к следующему вопросу.');
        END IF;
        v_elapsed := touch_question(p_id_attempt, p_id_qt, p_uid);
        SELECT qt.is_required, qt.time_limit, ty.uses_options, ty.is_numeric_answer, ty.is_text_answer
        INTO v_required, v_q_limit, v_uses_options, v_numeric, v_text
        FROM question_in_test qt JOIN question q ON q.id_question = qt.id_question
        JOIN question_type ty ON ty.type_id = q.type_id WHERE qt.id_qt = p_id_qt;
        IF v_required = 1 AND (v_q_limit IS NULL OR v_elapsed < v_q_limit) THEN
            IF v_numeric = 1 AND p_answer_number IS NULL THEN RAISE_APPLICATION_ERROR(-20314, 'Введите числовой ответ.'); END IF;
            IF v_text = 1 AND TRIM(p_answer_text) IS NULL THEN RAISE_APPLICATION_ERROR(-20315, 'Введите текстовый ответ.'); END IF;
        END IF;

        INSERT INTO answer (
            id_attempt, id_qt, answer_text, answer_number,
            answer_date, answer_time, is_checked
        ) VALUES (
            p_id_attempt, p_id_qt, p_answer_text, p_answer_number,
            SYSDATE, v_elapsed, 0
        )
        RETURNING id_answer INTO v_answer_id;

        RETURN v_answer_id;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20307, 'Ответ уже сохранен');
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20308, 'Попытка не найдена');
    END;

    PROCEDURE save_selected_option(p_id_answer NUMBER, p_id_option NUMBER) IS
        v_id_question NUMBER;
        v_opt_question NUMBER;
    BEGIN
        SELECT qt.id_question
        INTO v_id_question
        FROM answer a
        JOIN question_in_test qt ON qt.id_qt = a.id_qt
        WHERE a.id_answer = p_id_answer;

        SELECT id_question INTO v_opt_question
        FROM answer_option
        WHERE id_option = p_id_option;

        IF v_id_question <> v_opt_question THEN
            RAISE_APPLICATION_ERROR(-20309, 'Вариант не относится к вопросу ответа');
        END IF;

        INSERT INTO answer_selected_option (id_answer, id_option)
        VALUES (p_id_answer, p_id_option);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20310, 'Ответ или вариант не найден');
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    FUNCTION check_answer(p_id_answer NUMBER) RETURN NUMBER IS
        v_uses_options NUMBER;
        v_is_multi_select NUMBER;
        v_is_numeric_answer NUMBER;
        v_is_text_answer NUMBER;
        v_correct_text question.correct_text%TYPE;
        v_correct_number NUMBER;
        v_tolerance NUMBER;
        v_answer_text answer.answer_text%TYPE;
        v_answer_number NUMBER;
        v_cnt NUMBER;
        v_correct NUMBER := 0;
        v_selected_wrong NUMBER := 0;
        v_selected_correct NUMBER := 0;
        v_total_correct NUMBER := 0;
    BEGIN
        SELECT qt_type.uses_options, qt_type.is_multi_select, qt_type.is_numeric_answer, qt_type.is_text_answer,
               q.correct_text, q.correct_number, NVL(q.tolerance, 0), a.answer_text, a.answer_number
        INTO v_uses_options, v_is_multi_select, v_is_numeric_answer, v_is_text_answer,
             v_correct_text, v_correct_number, v_tolerance, v_answer_text, v_answer_number
        FROM answer a
        JOIN question_in_test qt ON qt.id_qt = a.id_qt
        JOIN question q ON q.id_question = qt.id_question
        JOIN question_type qt_type ON qt_type.type_id = q.type_id
        WHERE a.id_answer = p_id_answer;

        IF v_uses_options = 1 AND v_is_multi_select = 0 THEN
            SELECT COUNT(*)
            INTO v_cnt
            FROM answer_selected_option aso
            JOIN answer_option ao ON ao.id_option = aso.id_option
            WHERE aso.id_answer = p_id_answer
              AND ao.is_correct = 1;
            IF v_cnt = 1 THEN
                SELECT COUNT(*)
                INTO v_cnt
                FROM answer_selected_option
                WHERE id_answer = p_id_answer;
                IF v_cnt = 1 THEN
                    v_correct := 1;
                END IF;
            END IF;
        ELSIF v_uses_options = 1 AND v_is_multi_select = 1 THEN
            SELECT COUNT(*) INTO v_selected_wrong
            FROM answer_selected_option aso
            JOIN answer_option ao ON ao.id_option = aso.id_option
            WHERE aso.id_answer = p_id_answer
              AND ao.is_correct = 0;
            IF v_selected_wrong = 0 THEN
                SELECT COUNT(*) INTO v_selected_correct
                FROM answer_selected_option aso
                JOIN answer_option ao ON ao.id_option = aso.id_option
                WHERE aso.id_answer = p_id_answer
                  AND ao.is_correct = 1;
                SELECT COUNT(*) INTO v_total_correct
                FROM answer_option ao
                JOIN answer a ON a.id_answer = p_id_answer
                JOIN question_in_test qt ON qt.id_qt = a.id_qt
                WHERE ao.id_question = qt.id_question
                  AND ao.is_correct = 1;
                IF v_total_correct > 0 AND v_selected_correct = v_total_correct THEN
                    v_correct := 1;
                END IF;
            END IF;
        ELSIF v_is_text_answer = 1 THEN
            IF v_correct_text IS NOT NULL AND LOWER(TRIM(v_answer_text)) = LOWER(TRIM(v_correct_text)) THEN
                v_correct := 1;
            END IF;
        ELSIF v_is_numeric_answer = 1 THEN
            IF v_answer_number IS NOT NULL
               AND v_correct_number IS NOT NULL
               AND ABS(v_answer_number - v_correct_number) <= v_tolerance THEN
                v_correct := 1;
            END IF;
        END IF;

        UPDATE answer SET is_correct = v_correct, is_checked = 1 WHERE id_answer = p_id_answer;
        RETURN v_correct;
    END;

    FUNCTION calc_answer_score(p_id_answer NUMBER) RETURN NUMBER IS
        v_is_multi_select NUMBER;
        v_weight NUMBER;
        v_q_time_limit NUMBER;
        v_ans_time NUMBER;
        v_score NUMBER := 0;
        v_correct NUMBER;
        v_selected_wrong NUMBER := 0;
        v_selected_correct NUMBER := 0;
        v_total_correct NUMBER := 0;
    BEGIN
        SELECT qt_type.is_multi_select, qt.weight, qt.time_limit, NVL(a.answer_time, 0)
        INTO v_is_multi_select, v_weight, v_q_time_limit, v_ans_time
        FROM answer a
        JOIN question_in_test qt ON qt.id_qt = a.id_qt
        JOIN question q ON q.id_question = qt.id_question
        JOIN question_type qt_type ON qt_type.type_id = q.type_id
        WHERE a.id_answer = p_id_answer;

        IF v_q_time_limit IS NOT NULL AND v_ans_time >= v_q_time_limit THEN
            v_score := 0;
            UPDATE answer SET earned_score = v_score, is_correct = 0, is_checked = 1 WHERE id_answer = p_id_answer;
            RETURN v_score;
        END IF;

        v_correct := check_answer(p_id_answer);

        IF v_is_multi_select = 1 THEN
            SELECT COUNT(*) INTO v_selected_wrong
            FROM answer_selected_option aso
            JOIN answer_option ao ON ao.id_option = aso.id_option
            WHERE aso.id_answer = p_id_answer AND ao.is_correct = 0;

            IF v_selected_wrong = 0 THEN
                SELECT COUNT(*) INTO v_selected_correct
                FROM answer_selected_option aso
                JOIN answer_option ao ON ao.id_option = aso.id_option
                WHERE aso.id_answer = p_id_answer AND ao.is_correct = 1;
                SELECT COUNT(*) INTO v_total_correct
                FROM answer_option ao
                JOIN answer a ON a.id_answer = p_id_answer
                JOIN question_in_test qt ON qt.id_qt = a.id_qt
                WHERE ao.id_question = qt.id_question
                  AND ao.is_correct = 1;
                IF v_total_correct > 0 THEN
                    v_score := v_weight * v_selected_correct / v_total_correct;
                END IF;
            END IF;
        ELSE
            IF v_correct = 1 THEN
                v_score := v_weight;
            ELSE
                v_score := 0;
            END IF;
        END IF;

        UPDATE answer SET earned_score = v_score WHERE id_answer = p_id_answer;
        RETURN v_score;
    END;

    PROCEDURE calc_result(p_id_attempt NUMBER) IS
        v_total_weight NUMBER := 0;
        v_total_score NUMBER := 0;
        v_percent NUMBER := 0;
    BEGIN
        FOR r IN (
            SELECT a.id_answer
            FROM answer a
            WHERE a.id_attempt = p_id_attempt
        ) LOOP
            v_total_score := v_total_score + NVL(calc_answer_score(r.id_answer), 0);
        END LOOP;

        SELECT NVL(SUM(qt.weight), 0)
        INTO v_total_weight
        FROM question_in_test qt
        JOIN attempt at ON at.id_test = qt.id_test
        WHERE at.id_attempt = p_id_attempt;

        IF v_total_weight > 0 THEN
            v_percent := ROUND(v_total_score / v_total_weight * 100, 2);
        END IF;

        UPDATE attempt
        SET score = v_total_score,
            percent_result = v_percent
        WHERE id_attempt = p_id_attempt;
    END;

    PROCEDURE finish_attempt(p_id_attempt NUMBER, p_uid NUMBER) IS
        v_status attempt.status%TYPE;
        v_attempt_uid attempt.user_id%TYPE;
        v_started DATE;
        v_time_limit NUMBER;
        v_new_status VARCHAR2(30);
        v_finished_in_time NUMBER := 1;
        v_missing NUMBER;
    BEGIN
        SELECT a.status, a.user_id, a.start_date, t.time_limit
        INTO v_status, v_attempt_uid, v_started, v_time_limit
        FROM attempt a
        JOIN test t ON t.id_test = a.id_test
        WHERE a.id_attempt = p_id_attempt FOR UPDATE OF a.status;

        IF v_attempt_uid <> p_uid AND check_admin_role(p_uid) <> 1 THEN
            RAISE_APPLICATION_ERROR(-20313, 'Попытка не принадлежит пользователю');
        END IF;

        IF v_status <> 'STARTED' THEN
            RETURN;
        END IF;

        v_new_status := 'FINISHED';
        IF v_time_limit IS NOT NULL
           AND (SYSDATE - v_started) * 86400 >= v_time_limit THEN
            v_new_status := 'TIME_EXPIRED';
            v_finished_in_time := 0;
        END IF;

        IF v_new_status = 'FINISHED' THEN
            SELECT COUNT(*) INTO v_missing FROM question_in_test qt
            JOIN attempt a ON a.id_test = qt.id_test
            WHERE a.id_attempt = p_id_attempt AND qt.is_required = 1
              AND NOT EXISTS (SELECT 1 FROM answer x WHERE x.id_attempt = p_id_attempt AND x.id_qt = qt.id_qt);
            IF v_missing > 0 THEN RAISE_APPLICATION_ERROR(-20316, 'Сначала ответьте на обязательные вопросы.'); END IF;
        END IF;

        UPDATE attempt
        SET end_date = SYSDATE,
            status = v_new_status,
            finished_in_time = v_finished_in_time
        WHERE id_attempt = p_id_attempt;

        calc_result(p_id_attempt);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20308, 'Попытка не найдена');
    END;

    FUNCTION get_user(p_uid NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT u.user_id, u.user_name, u.id_role, r.role_name, r.role_description, u.is_active
            FROM users u
            JOIN role r ON r.id_role = u.id_role
            WHERE u.user_id = p_uid;
        RETURN rc;
    END;

    FUNCTION list_categories RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR SELECT id_category, category_name, category_description FROM category ORDER BY category_name;
        RETURN rc;
    END;

    FUNCTION list_difficulty_levels RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR SELECT id_level, level_name FROM difficulty_level ORDER BY id_level;
        RETURN rc;
    END;

    FUNCTION list_question_types RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR SELECT type_id, type_name, type_code, uses_options, is_multi_select, is_numeric_answer, is_text_answer FROM question_type ORDER BY type_id;
        RETURN rc;
    END;

    FUNCTION list_author_questions(p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT q.id_question, q.question_text, qt.type_name, c.category_name, d.level_name, q.is_active, q.image_path
            FROM question q
            JOIN question_type qt ON qt.type_id = q.type_id
            JOIN category c ON c.id_category = q.id_category
            JOIN difficulty_level d ON d.id_level = q.id_level
            WHERE (q.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
            ORDER BY q.id_question DESC;
        RETURN rc;
    END;

    FUNCTION get_author_question(p_id_question NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT q.id_question, q.question_text, q.explanation, q.correct_text, q.correct_number, q.tolerance,
                   q.is_active, qt.type_name, c.category_name, d.level_name, q.image_path, qt.uses_options,
                   (SELECT COUNT(*) FROM question_in_test x JOIN test t ON t.id_test = x.id_test
                    WHERE x.id_question = q.id_question AND (t.is_active = 1 OR EXISTS (SELECT 1 FROM attempt a WHERE a.id_test = t.id_test)))
            FROM question q
            JOIN question_type qt ON qt.type_id = q.type_id
            JOIN category c ON c.id_category = q.id_category
            JOIN difficulty_level d ON d.id_level = q.id_level
            WHERE q.id_question = p_id_question AND (q.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        RETURN rc;
    END;

    FUNCTION list_answer_options(p_id_question NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT ao.id_option, ao.option_text, ao.is_correct
            FROM answer_option ao
            JOIN question q ON q.id_question = ao.id_question
            WHERE ao.id_question = p_id_question
              AND (q.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
            ORDER BY ao.id_option;
        RETURN rc;
    END;

    FUNCTION list_available_tests(p_uid NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT t.id_test, t.test_name, t.test_description, c.category_name, d.level_name,
                   t.time_limit, t.attempt_limit, (SELECT COUNT(*) FROM question_in_test qt WHERE qt.id_test = t.id_test), t.show_feedback,
                   NVL((SELECT MAX(a.attempt_number) FROM attempt a WHERE a.user_id = p_uid AND a.id_test = t.id_test), 0) AS used_attempts
            FROM test t
            LEFT JOIN category c ON c.id_category = t.id_category
            LEFT JOIN difficulty_level d ON d.id_level = t.id_level
            WHERE check_access(t.id_test, p_uid) = 1
            ORDER BY t.id_test DESC;
        RETURN rc;
    END;

    FUNCTION get_available_test(p_id_test NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT t.id_test, t.test_name, t.test_description, c.category_name, d.level_name,
                   t.time_limit, t.attempt_limit, (SELECT COUNT(*) FROM question_in_test qt WHERE qt.id_test = t.id_test), t.show_feedback,
                   NVL((SELECT MAX(a.attempt_number) FROM attempt a WHERE a.user_id = p_uid AND a.id_test = t.id_test), 0) AS used_attempts
            FROM test t
            LEFT JOIN category c ON c.id_category = t.id_category
            LEFT JOIN difficulty_level d ON d.id_level = t.id_level
            WHERE t.id_test = p_id_test AND check_access(t.id_test, p_uid) = 1;
        RETURN rc;
    END;

    FUNCTION get_attempt(p_id_attempt NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT a.id_attempt, a.status, a.start_date, a.end_date, t.id_test, t.test_name,
                   t.time_limit, FLOOR((SYSDATE - a.start_date) * 86400) AS elapsed_seconds,
                   CASE WHEN t.time_limit IS NULL THEN NULL ELSE GREATEST(0, t.time_limit - FLOOR((SYSDATE - a.start_date) * 86400)) END AS remaining_seconds,
                   a.user_id, (SELECT u.user_name FROM users u WHERE u.user_id = a.user_id)
            FROM attempt a
            JOIN test t ON t.id_test = a.id_test
            WHERE a.id_attempt = p_id_attempt AND (a.user_id = p_uid OR check_admin_role(p_uid) = 1);
        RETURN rc;
    END;

    FUNCTION list_attempt_questions(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT qt.id_qt, qt.order_num, qt.weight, qt.time_limit,
                   q.id_question, q.question_text, q.type_id, q.explanation,
                   qt_type.uses_options, qt_type.is_multi_select, qt_type.is_numeric_answer, qt_type.is_text_answer,
                   q.image_path, qt.is_required
            FROM question_in_test qt
            JOIN question q ON q.id_question = qt.id_question
            JOIN question_type qt_type ON qt_type.type_id = q.type_id
            JOIN attempt a ON a.id_test = qt.id_test
            WHERE a.id_attempt = p_id_attempt
            ORDER BY qt.order_num;
        RETURN rc;
    END;

    FUNCTION list_attempt_answers(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT id_answer, id_qt, answer_text, answer_number, is_correct, earned_score, answer_time
            FROM answer
            WHERE id_attempt = p_id_attempt;
        RETURN rc;
    END;

    FUNCTION list_attempt_selected_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT aso.id_answer, aso.id_option, ao.option_text
            FROM answer_selected_option aso
            JOIN answer a ON a.id_answer = aso.id_answer
            JOIN answer_option ao ON ao.id_option = aso.id_option
            WHERE a.id_attempt = p_id_attempt
            ORDER BY ao.id_option;
        RETURN rc;
    END;

    FUNCTION list_attempt_question_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT ao.id_option, ao.id_question, ao.option_text
            FROM answer_option ao
            JOIN question q ON q.id_question = ao.id_question
            JOIN question_in_test qt ON qt.id_question = q.id_question
            JOIN attempt a ON a.id_test = qt.id_test
            WHERE a.id_attempt = p_id_attempt
            ORDER BY ao.id_option;
        RETURN rc;
    END;

    FUNCTION get_attempt_result(p_id_attempt NUMBER, p_uid NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT a.id_attempt, a.attempt_number, a.start_date, a.end_date, a.status, a.score, a.percent_result,
                   t.id_test, t.test_name, CASE WHEN check_admin_role(p_uid) = 1 THEN 1 ELSE t.show_feedback END,
                   NVL((
                       SELECT AVG(x.percent_result)
                       FROM attempt x
                       WHERE x.id_test = a.id_test
                         AND EXISTS (
                             SELECT 1
                             FROM attempt_status s
                             WHERE s.status_code = x.status
                               AND s.is_successful = 1
                         )
                         AND x.percent_result IS NOT NULL
                   ), 0) AS avg_percent,
                   a.user_id, (SELECT u.user_name FROM users u WHERE u.user_id = a.user_id)
            FROM attempt a
            JOIN test t ON t.id_test = a.id_test
            WHERE a.id_attempt = p_id_attempt AND (a.user_id = p_uid OR check_admin_role(p_uid) = 1);
        RETURN rc;
    END;

    FUNCTION list_result_answers(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT qt.order_num, q.question_text, q.type_id, a.id_answer, a.answer_text, a.answer_number,
                   a.is_correct, a.earned_score, q.correct_text, q.correct_number, q.explanation,
                   qt_type.uses_options, qt_type.is_multi_select, qt_type.is_numeric_answer, qt_type.is_text_answer,
                   q.image_path
            FROM question_in_test qt
            JOIN question q ON q.id_question = qt.id_question
            JOIN question_type qt_type ON qt_type.type_id = q.type_id
            JOIN attempt at ON at.id_test = qt.id_test
            LEFT JOIN answer a ON a.id_qt = qt.id_qt AND a.id_attempt = at.id_attempt
            WHERE at.id_attempt = p_id_attempt
            ORDER BY qt.order_num;
        RETURN rc;
    END;

    FUNCTION list_result_selected_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT aso.id_answer, ao.option_text
            FROM answer_selected_option aso
            JOIN answer_option ao ON ao.id_option = aso.id_option
            JOIN answer a ON a.id_answer = aso.id_answer
            WHERE a.id_attempt = p_id_attempt
            ORDER BY ao.id_option;
        RETURN rc;
    END;

    FUNCTION list_result_correct_options(p_id_attempt NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT qt.order_num, ao.option_text
            FROM question_in_test qt
            JOIN attempt at ON at.id_test = qt.id_test
            JOIN answer_option ao ON ao.id_question = qt.id_question
            WHERE at.id_attempt = p_id_attempt
              AND ao.is_correct = 1
            ORDER BY qt.order_num, ao.id_option;
        RETURN rc;
    END;

    FUNCTION list_user_attempts(p_uid NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT a.id_attempt, t.test_name, a.attempt_number, a.status, a.score, a.percent_result, a.start_date, a.end_date
            FROM attempt a
            JOIN test t ON t.id_test = a.id_test
            WHERE a.user_id = p_uid
            ORDER BY a.id_attempt DESC;
        RETURN rc;
    END;

    FUNCTION list_author_tests(p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT t.id_test, t.test_name, t.test_description, t.is_active,
                   t.question_count, t.attempt_limit, t.time_limit, t.show_feedback,
                   c.category_name, d.level_name
            FROM test t
            LEFT JOIN category c ON c.id_category = t.id_category
            LEFT JOIN difficulty_level d ON d.id_level = t.id_level
            WHERE (t.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
            ORDER BY t.id_test DESC;
        RETURN rc;
    END;

    FUNCTION get_author_test(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT t.id_test, t.test_name, t.test_description, t.is_active, t.question_count, t.attempt_limit, t.time_limit,
                   t.show_feedback, c.category_name, d.level_name,
                   (SELECT COUNT(*) FROM attempt a WHERE a.id_test = t.id_test)
            FROM test t
            LEFT JOIN category c ON c.id_category = t.id_category
            LEFT JOIN difficulty_level d ON d.id_level = t.id_level
            WHERE t.id_test = p_id_test AND (t.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        RETURN rc;
    END;

    FUNCTION list_test_questions(p_id_test NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT qt.id_qt, qt.order_num, qt.weight, qt.is_required, qt.time_limit, q.id_question, q.question_text, q.image_path
            FROM question_in_test qt
            JOIN question q ON q.id_question = qt.id_question
            WHERE qt.id_test = p_id_test
            ORDER BY qt.order_num;
        RETURN rc;
    END;

    FUNCTION list_selected_test_questions(p_id_test NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT qt.order_num, q.id_question, q.question_text, qt.weight, qt.is_required, qt.time_limit, q.image_path
            FROM question_in_test qt
            JOIN question q ON q.id_question = qt.id_question
            WHERE qt.id_test = p_id_test
            ORDER BY qt.order_num;
        RETURN rc;
    END;

    FUNCTION list_question_pool(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT q.id_question, q.question_text, q.image_path
            FROM question q
            JOIN test t ON (t.uid_author = q.uid_author OR check_admin_role(p_uid_author) = 1)
            WHERE t.id_test = p_id_test
              AND (q.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
              AND q.is_active = 1
              AND NOT EXISTS (
                  SELECT 1 FROM question_in_test x WHERE x.id_test = p_id_test AND x.id_question = q.id_question
              )
            ORDER BY q.id_question DESC;
        RETURN rc;
    END;

    FUNCTION get_author_test_access_header(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT id_test, test_name
            FROM test
            WHERE id_test = p_id_test AND (uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1);
        RETURN rc;
    END;

    FUNCTION list_test_access(p_id_test NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT ta.user_id, u.user_name, ta.is_active, ta.granted_at
            FROM test_access ta
            JOIN users u ON u.user_id = ta.user_id
            WHERE ta.id_test = p_id_test
            ORDER BY ta.granted_at DESC;
        RETURN rc;
    END;

    FUNCTION get_test_statistics_summary(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT
                t.test_name,
                COUNT(a.id_attempt) AS total_attempts,
                SUM(CASE WHEN s.is_successful = 1 THEN 1 ELSE 0 END) AS finished_attempts,
                ROUND(AVG(CASE WHEN s.is_successful = 1 THEN a.score END), 2) AS avg_score,
                ROUND(AVG(CASE WHEN s.is_successful = 1 THEN a.percent_result END), 2) AS avg_percent,
                MIN(CASE WHEN s.is_successful = 1 THEN a.percent_result END) AS min_percent,
                MAX(CASE WHEN s.is_successful = 1 THEN a.percent_result END) AS max_percent
            FROM test t
            LEFT JOIN attempt a ON a.id_test = t.id_test
            LEFT JOIN attempt_status s ON s.status_code = a.status
            WHERE t.id_test = p_id_test
              AND (t.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
            GROUP BY t.test_name;
        RETURN rc;
    END;

    FUNCTION list_test_statistics_questions(p_id_test NUMBER, p_uid_author NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        OPEN rc FOR
            SELECT
                qt.order_num,
                q.question_text,
                COUNT(a.id_answer) AS total_answers,
                SUM(CASE WHEN a.is_correct = 1 THEN 1 ELSE 0 END) AS correct_answers,
                ROUND(
                    CASE WHEN COUNT(a.id_answer) = 0 THEN 0
                         ELSE SUM(CASE WHEN a.is_correct = 1 THEN 1 ELSE 0 END) / COUNT(a.id_answer) * 100
                    END, 2
                ) AS percent_correct,
                ROUND(AVG(a.answer_time), 2) AS avg_answer_time,
                ROUND(AVG(a.earned_score), 2) AS avg_earned_score
            FROM test t
            JOIN question_in_test qt ON qt.id_test = t.id_test
            JOIN question q ON q.id_question = qt.id_question
            LEFT JOIN answer a ON a.id_qt = qt.id_qt
                AND EXISTS (
                    SELECT 1
                    FROM attempt at
                    JOIN attempt_status s ON s.status_code = at.status
                    WHERE at.id_attempt = a.id_attempt
                      AND s.is_successful = 1
                )
            WHERE t.id_test = p_id_test
              AND (t.uid_author = p_uid_author OR check_admin_role(p_uid_author) = 1)
            GROUP BY qt.order_num, q.question_text
            ORDER BY qt.order_num;
        RETURN rc;
    END;

    FUNCTION list_admin_users(p_uid_admin NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        require_admin(p_uid_admin);

        OPEN rc FOR
            SELECT u.user_id, u.user_name, r.role_name, u.is_active, u.created_at
            FROM users u
            JOIN role r ON r.id_role = u.id_role
            ORDER BY u.user_id DESC;
        RETURN rc;
    END;

    FUNCTION list_admin_attempts(p_uid_admin NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        require_admin(p_uid_admin);
        OPEN rc FOR
            SELECT a.id_attempt, t.test_name, a.attempt_number, a.status,
                   a.score, a.percent_result, a.start_date, a.end_date,
                   a.user_id, u.user_name
            FROM attempt a
            JOIN test t ON t.id_test = a.id_test
            JOIN users u ON u.user_id = a.user_id
            ORDER BY a.id_attempt DESC;
        RETURN rc;
    END;

    FUNCTION list_admin_tests(p_uid_admin NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        require_admin(p_uid_admin);

        OPEN rc FOR
            SELECT t.id_test, t.test_name, u.user_name, t.is_active, t.created_at, t.attempt_limit, t.question_count
            FROM test t
            JOIN users u ON u.user_id = t.uid_author
            ORDER BY t.id_test DESC;
        RETURN rc;
    END;

    FUNCTION list_admin_questions(p_uid_admin NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        require_admin(p_uid_admin);

        OPEN rc FOR
            SELECT q.id_question, q.question_text, u.user_name, qt.type_name, q.is_active, q.created_at, q.image_path
            FROM question q
            JOIN users u ON u.user_id = q.uid_author
            JOIN question_type qt ON qt.type_id = q.type_id
            ORDER BY q.id_question DESC;
        RETURN rc;
    END;

    FUNCTION get_admin_statistics(p_uid_admin NUMBER) RETURN SYS_REFCURSOR IS
        rc SYS_REFCURSOR;
    BEGIN
        require_admin(p_uid_admin);

        OPEN rc FOR
            SELECT
                (SELECT COUNT(*) FROM users) AS users_total,
                (SELECT COUNT(*) FROM users WHERE is_active = 1) AS users_active,
                (SELECT COUNT(*) FROM test) AS tests_total,
                (SELECT COUNT(*) FROM test WHERE is_active = 1) AS tests_published,
                (SELECT COUNT(*) FROM question) AS questions_total,
                (SELECT COUNT(*) FROM attempt) AS attempts_total
            FROM dual;
        RETURN rc;
    END;

    PROCEDURE show_result(p_id_attempt NUMBER) IS
        v_test_name test.test_name%TYPE;
        v_attempt_number attempt.attempt_number%TYPE;
        v_status attempt.status%TYPE;
        v_score attempt.score%TYPE;
        v_percent attempt.percent_result%TYPE;
        v_avg_percent NUMBER;
    BEGIN
        SELECT t.test_name, a.attempt_number, a.status, a.score, a.percent_result
        INTO v_test_name, v_attempt_number, v_status, v_score, v_percent
        FROM attempt a
        JOIN test t ON t.id_test = a.id_test
        WHERE a.id_attempt = p_id_attempt;

        SELECT NVL(AVG(x.percent_result), 0)
        INTO v_avg_percent
        FROM attempt x
        WHERE x.id_test = (SELECT id_test FROM attempt WHERE id_attempt = p_id_attempt)
          AND EXISTS (
              SELECT 1
              FROM attempt_status s
              WHERE s.status_code = x.status
                AND s.is_successful = 1
          )
          AND x.percent_result IS NOT NULL;

        DBMS_OUTPUT.PUT_LINE('Тест: ' || v_test_name);
        DBMS_OUTPUT.PUT_LINE('Номер попытки: ' || v_attempt_number);
        DBMS_OUTPUT.PUT_LINE('Статус: ' || v_status);
        DBMS_OUTPUT.PUT_LINE('Балл: ' || NVL(v_score, 0));
        DBMS_OUTPUT.PUT_LINE('Процент: ' || NVL(v_percent, 0));
        DBMS_OUTPUT.PUT_LINE('Средний процент по тесту: ' || ROUND(v_avg_percent, 2));
        DBMS_OUTPUT.PUT_LINE('Разница: ' || ROUND(NVL(v_percent, 0) - v_avg_percent, 2));
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20400, 'Попытка не найдена');
    END;

    PROCEDURE show_user_attempts(p_uid NUMBER) IS
        v_found NUMBER := 0;
    BEGIN
        FOR rec IN (
            SELECT a.id_attempt, t.test_name, a.attempt_number, a.status, a.score, a.percent_result
            FROM attempt a
            JOIN test t ON t.id_test = a.id_test
            WHERE a.user_id = p_uid
            ORDER BY a.id_attempt DESC
        ) LOOP
            v_found := 1;
            DBMS_OUTPUT.PUT_LINE(
                'Попытка #' || rec.id_attempt ||
                ' | Тест: ' || rec.test_name ||
                ' | Номер: ' || rec.attempt_number ||
                ' | Статус: ' || rec.status ||
                ' | Балл: ' || NVL(rec.score, 0) ||
                ' | Процент: ' || NVL(rec.percent_result, 0)
            );
        END LOOP;

        IF v_found = 0 THEN
            DBMS_OUTPUT.PUT_LINE('У пользователя нет попыток.');
        END IF;
    END;
    PROCEDURE show_test_statistics(p_id_test NUMBER) IS
        v_test_name test.test_name%TYPE;
        v_total_attempts NUMBER;
        v_finished_attempts NUMBER;
        v_avg_score NUMBER;
        v_avg_percent NUMBER;
        v_min_percent NUMBER;
        v_max_percent NUMBER;
    BEGIN
        SELECT test_name INTO v_test_name FROM test WHERE id_test = p_id_test;

        SELECT
            COUNT(*),
            SUM(CASE WHEN s.is_successful = 1 THEN 1 ELSE 0 END),
            ROUND(AVG(CASE WHEN s.is_successful = 1 THEN score END), 2),
            ROUND(AVG(CASE WHEN s.is_successful = 1 THEN percent_result END), 2),
            MIN(CASE WHEN s.is_successful = 1 THEN percent_result END),
            MAX(CASE WHEN s.is_successful = 1 THEN percent_result END)
        INTO
            v_total_attempts,
            v_finished_attempts,
            v_avg_score,
            v_avg_percent,
            v_min_percent,
            v_max_percent
        FROM attempt a
        LEFT JOIN attempt_status s ON s.status_code = a.status
        WHERE a.id_test = p_id_test;

        DBMS_OUTPUT.PUT_LINE('Статистика теста: ' || v_test_name || ' (#' || p_id_test || ')');
        DBMS_OUTPUT.PUT_LINE('Попыток: ' || NVL(v_total_attempts, 0));
        DBMS_OUTPUT.PUT_LINE('Завершено: ' || NVL(v_finished_attempts, 0));
        DBMS_OUTPUT.PUT_LINE('Средний балл: ' || NVL(v_avg_score, 0));
        DBMS_OUTPUT.PUT_LINE('Средний процент: ' || NVL(v_avg_percent, 0));
        DBMS_OUTPUT.PUT_LINE('Минимальный процент: ' || NVL(v_min_percent, 0));
        DBMS_OUTPUT.PUT_LINE('Максимальный процент: ' || NVL(v_max_percent, 0));

        FOR q IN (
            SELECT
                qt.order_num,
                q.question_text,
                COUNT(a.id_answer) AS total_answers,
                SUM(CASE WHEN a.is_correct = 1 THEN 1 ELSE 0 END) AS correct_answers,
                ROUND(
                    CASE WHEN COUNT(a.id_answer) = 0 THEN 0
                         ELSE SUM(CASE WHEN a.is_correct = 1 THEN 1 ELSE 0 END) / COUNT(a.id_answer) * 100
                    END, 2
                ) AS percent_correct,
                ROUND(AVG(a.answer_time), 2) AS avg_answer_time,
                ROUND(AVG(a.earned_score), 2) AS avg_earned_score
            FROM question_in_test qt
            JOIN question q ON q.id_question = qt.id_question
            LEFT JOIN answer a ON a.id_qt = qt.id_qt
                AND EXISTS (
                    SELECT 1
                    FROM attempt at
                    JOIN attempt_status s ON s.status_code = at.status
                    WHERE at.id_attempt = a.id_attempt
                      AND s.is_successful = 1
                )
            WHERE qt.id_test = p_id_test
            GROUP BY qt.order_num, q.question_text
            ORDER BY qt.order_num
        ) LOOP
            DBMS_OUTPUT.PUT_LINE(
                'Q' || q.order_num ||
                ' | ' || q.question_text ||
                ' | Ответов: ' || NVL(q.total_answers, 0) ||
                ' | Правильных: ' || NVL(q.correct_answers, 0) ||
                ' | %: ' || NVL(q.percent_correct, 0) ||
                ' | Ср. время: ' || NVL(q.avg_answer_time, 0) ||
                ' | Ср. балл: ' || NVL(q.avg_earned_score, 0)
            );
        END LOOP;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20401, 'Тест не найден');
    END;
END quiz_platform;
/

SELECT object_name, object_type, status FROM user_objects
WHERE object_name = 'QUIZ_PLATFORM' ORDER BY object_type;
SELECT name, type, line, position, text FROM user_errors
WHERE name = 'QUIZ_PLATFORM' ORDER BY type, sequence;
